### ISSUE TITLE
[Performance Enhancement] Generating GL Transactions Report is too slow

### ISSUE THREAD

**Issue by wei9528** [appdevdesigns/app_builder#122]
Testing Environment:
MacOS, Chrome. Internet speed: avg. 7-8 Mbps.

To Replicate:
1. Prepare large dataset. >3000 Journal Entries.
2. Submit the unsbumitted batches. 
3. Set the Submitted batches to Complete. 
4. Select Active month, run GL Transactions report, the spinning circle keeps running.

**Comment by wongpratan** [comment]
I removed **JE for Reports** and **J for Reports** data collections from **GL Transactions Report (one month) docx** widget because **JE for Reports** might be the bottleneck of this performance issue. It loads all, no any filter and no parent data collection.
And I updated the DOCX template to render **JE Archive** by pull from **Balance for Reports** who has connected JE archive data.

**Comment by wongpratan** [comment]
I removed **JE for Reports** and **J for Reports** data collections from **GL Transactions Report (one month)** docx widget because **JE for Reports** might be the bottleneck of this performance issue. It loads all, no any filter and no parent data collection.
And I updated the DOCX template to render **JE Archive** by pull from **Balance for Reports** who has connected JE archive data.
We can get **Journal Code** from **Batch for Reports** directly because its connected field has custom index of Journal Code.
