### ISSUE TITLE
Data Collections based on Queries cannot be linked using a custom index

### ISSUE THREAD

**Issue by nh758** [appdevdesigns/app_builder#147]
**Describe the bug**
Data Collections based on Queries cannot be linked when connected using a custom index.

**To Reproduce**
1. Add two objects and connect them using a custom key
2. Add a query for one of the objects, adding the connection to the second object to the query
3. Add a data collection for the second object and select cursor fix [Default to First Record].
3. Add a data collection for the query and link it to the first data collection.
4. Nothing loads

**Expected behavior**
Should see records connected with the second data collection

**Server**
Trial

**Screenshots**
![image](https://user-images.githubusercontent.com/10155226/91541404-806f9400-e946-11ea-801b-f6aa73e9c844.png)

**Additional context**
Needed for Accounting 'Balance for Netsuite' Data Collection, worked before switching to custom indexes

**Comment by jamesduncan** [comment]
This bug is specifically related to the Data Collection admin. The data does load fine in the live view. There could be a few different factors. One is that we are relying on the event of the setCursor to be fired before this Data Collection will attempt to load because it knows that its parent data collection has a static cursor (or default at least). I don't know if that even is ever fired because I don't know if we preload linked data collections in the admin. The other issue that could be related to this is we are replacing the data grid with newly loaded server data when we click on a data collection. I don't know if that means we are clearing out a single data collection and replacing it with the settings of the new one each time we click to a new data collection in the admin or it could be that we don't have the view IDs unique so we are inadvertently doing that. In debug mode Webix is complaining a lot about the Data Collection admin's view ids not being unique when you switch between data collections.
