### ISSUE TITLE
[Accounting App Performance] Enhance data loading time 

### ISSUE THREAD

**Issue by wei9528** [appdevdesigns/app_builder#187]
As the amount of data increases on a monthly basis, some pages are very slow to load several months data, i.e. View Entries and Balances pages, and it takes over 10 mins to load a report. 
To offer better user experience, we need to improve the app response time. 
One way is View Entries and Balances pages just display data in the current month and previous month.

**Comment by nh758** [comment]
Performance is slow because Load All is used on the data collection. Load All is needed for rendering the DOCX report and exporting CSV file. Both are currently happening client side.

Pong will add a CSV export widget so that a load all data collection in a grid is not needed.

DOCX rendering could be moved server side however we may be moving away from that widget as we add report building to the platform.

**Comment by wongpratan** [comment]
https://github.com/appdevdesigns/app_builder/blob/master/api/controllers/ABCsvController.js

The new CSV export widget should be added.

**Comment by wei9528** [comment]
It only takes 3-5 seconds to show data on the View Entries page. 
However, still unable to filter data on the View Entries page, after entering a filter, after running several minutes, the page will stop responding.
