### ISSUE TITLE
Label widget text missing after importing app

### ISSUE THREAD

**Issue by nh758** [appdevdesigns/app_builder#195]
Label widgets have been reset to there default value *text in Accounting App on experimental. It seems like this would have happened during the import process.

**See the Issue**
On Experimental go to Accounting > Reports > GL Transactions:
![image](https://user-images.githubusercontent.com/10155226/94763479-87217900-03d4-11eb-929b-ca3837b10cf0.png)

Compared to Trial:
![image](https://user-images.githubusercontent.com/10155226/94763499-96082b80-03d4-11eb-958d-3997ee0e9bd9.png)

**Server**
Experimental

**Comment by jamesduncan** [comment]
It seems for the Accounting App this is the only label that is having problems...this type of change is okay to correct on experimental server and the new app JSON that we export to use for the app will have the correction in place.

**Comment by jamesduncan** [comment]
More specifically this issue has to do with the app reading the label from the definitions. The label is stored correctly in the database but I am wondering if App Builder is not taking into account that the data is stored in a translation object since the field is multilingual. Johnny can you take a look and see if you can identify why the noArango app definition isn't being read properly...I have verified that it properly updates the database when you edit the placeholder "*text" to something else and the UI even updates in the preview area...but when you reload the app it seems to fall back to the default "*text" each time even though the data is correct in the database.

**Comment by jamesduncan** [comment]
This has been fixed in the noArango branch.
